# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

x = torch.rand(7,7)
x, x.shape


# Create random tensor


(tensor([[0.2949, 0.9413, 0.0891, 0.9027, 0.8626, 0.7812, 0.7692],
         [0.5361, 0.1059, 0.0541, 0.9508, 0.4613, 0.2848, 0.0194],
         [0.4426, 0.7306, 0.4542, 0.2848, 0.1849, 0.5309, 0.1372],
         [0.4470, 0.7655, 0.4723, 0.3733, 0.2829, 0.9585, 0.8570],
         [0.1978, 0.2285, 0.3656, 0.4889, 0.5617, 0.6723, 0.2784],
         [0.9417, 0.5684, 0.8866, 0.6921, 0.5774, 0.8348, 0.5837],
         [0.2253, 0.5280, 0.4368, 0.8535, 0.9276, 0.2038, 0.9445]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
x_t = x.T

# Perform matrix multiplication 
z = x@x_t
x,x_t,z

(tensor([[0.2949, 0.9413, 0.0891, 0.9027, 0.8626, 0.7812, 0.7692],
         [0.5361, 0.1059, 0.0541, 0.9508, 0.4613, 0.2848, 0.0194],
         [0.4426, 0.7306, 0.4542, 0.2848, 0.1849, 0.5309, 0.1372],
         [0.4470, 0.7655, 0.4723, 0.3733, 0.2829, 0.9585, 0.8570],
         [0.1978, 0.2285, 0.3656, 0.4889, 0.5617, 0.6723, 0.2784],
         [0.9417, 0.5684, 0.8866, 0.6921, 0.5774, 0.8348, 0.5837],
         [0.2253, 0.5280, 0.4368, 0.8535, 0.9276, 0.2038, 0.9445]]),
 tensor([[0.2949, 0.5361, 0.4426, 0.4470, 0.1978, 0.9417, 0.2253],
         [0.9413, 0.1059, 0.7306, 0.7655, 0.2285, 0.5684, 0.5280],
         [0.0891, 0.0541, 0.4542, 0.4723, 0.3656, 0.8866, 0.4368],
         [0.9027, 0.9508, 0.2848, 0.3733, 0.4889, 0.6921, 0.8535],
         [0.8626, 0.4613, 0.1849, 0.2829, 0.5617, 0.5774, 0.9276],
         [0.7812, 0.2848, 0.5309, 0.9585, 0.6723, 0.8348, 0.2038],
         [0.7692, 0.0194, 0.1372, 0.8570, 0.2784, 0.5837, 0.9445]]),
 tensor([[3.7417, 1.7562, 1.7955, 2.8834, 1.9711, 3.1156, 

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
torch.manual_seed(42)


# Create two random tensors
x = torch.rand(3,5)
torch.manual_seed(42)
y = torch.rand(3,5)
y == x
# Matrix multiply tensors
y.mm(x.T)


tensor([[2.8349, 2.0233, 2.5345],
        [2.0233, 1.9596, 2.0367],
        [2.5345, 2.0367, 2.8532]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [22]:
# Set random seed on the GPU
torch.mps.manual_seed(42)
# Create two random tensors on GPU
x = torch.rand(3,5, device='mps')
torch.mps.manual_seed(42)
z = torch.rand(3,5, device='mps')

x,z, x==z

(tensor([[8.1718e-01, 5.8811e-01, 5.5805e-01, 7.6914e-01, 3.3936e-01],
         [4.5596e-01, 6.7508e-01, 4.4060e-04, 4.0876e-01, 1.7912e-01],
         [5.9732e-01, 8.4722e-01, 4.6701e-01, 2.0730e-01, 4.2425e-01]],
        device='mps:0'),
 tensor([[8.1718e-01, 5.8811e-01, 5.5805e-01, 7.6914e-01, 3.3936e-01],
         [4.5596e-01, 6.7508e-01, 4.4060e-04, 4.0876e-01, 1.7912e-01],
         [5.9732e-01, 8.4722e-01, 4.6701e-01, 2.0730e-01, 4.2425e-01]],
        device='mps:0'),
 tensor([[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]], device='mps:0'))


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed
torch.mps.manual_seed(1234)


# Check for access to GPU
x = torch.rand(2,3, device='mps');
y = torch.rand(2,3, device='mps');

# Create two random tensors on GPU
x, y

(tensor([[0.4794, 0.7608, 0.8283],
         [0.8029, 0.6423, 0.0597]], device='mps:0'),
 tensor([[0.0223, 0.9878, 0.2711],
         [0.9123, 0.7672, 0.8879]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
Z=x @ y.T 
Z


tensor([[0.9868, 1.7565],
        [0.6685, 1.2782]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [32]:
# Find max
Z.min(), Z.max()
# Find min


(tensor(0.6685, device='mps:0'), tensor(1.7565, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
Z.argmin(), Z.argmax()



# Find arg min


(tensor(2, device='mps:0'), tensor(1, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [37]:
# Set seed
torch.manual_seed(7)




# Create random tensor
X=torch.rand(1,1,1,10)


# Remove single dimensions
Z = X.reshape(10)


# Print out tensors and their shapes
X, X.shape,Z,  Z.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))